### ISSUE TITLE
Joining community discussion on osm forum

### ISSUE THREAD

**Issue by mmd-osm** [fossgis/new.openstreetmap.de#1]
Maybe you want to join the community discussion over at: https://forum.openstreetmap.org/viewtopic.php?id=74686

**Comment by TheFireCircle** [comment]
Hallo, ich bin der Beitragsersteller dieser Diskussion und habe initiiert, dass dieses Repository für ein neues Design erstellt wird.

**Comment by dex2000** [comment]
Gibts auch ne (sub)Domain dazu wo man sich das anschauen könnte?

**Comment by TheFireCircle** [comment]
@pka wäre das möglich? Z. B. via https://pages.github.com/
Oder das man wirklich eine temporäre Subdomäne (new.openstreetmap.de) erstellt, wo die Seite zu sehen ist.
