### ISSUE TITLE
Menü ohne Rand

### ISSUE THREAD

**Issue by pka** [fossgis/new.openstreetmap.de#2]
Ich fände das Menü ohne weissen Hintergrund und Rahmen schöner:

![image](https://user-images.githubusercontent.com/19007/156943378-6dc01a68-55ed-4817-a7f0-7a8f6ae6b74b.png)

**Comment by TheFireCircle** [comment]
Mit dem weißen Hintergrund der Navigationsleiste wollte ich eine visuelle Trennung zum Header schaffen. Mir erscheinen ohne Abtrennung zum Header die Menüpunkte etwas "lose".
Gerne können wir diesen Verbesserungsvorschlag auch noch mit anderen Interessierten diskutieren.
